// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using workout_planner.Server.Database;

#nullable disable

namespace workout_planner.Server.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    [Migration("20260309073651_Workout-Model")]
    partial class WorkoutModel
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ExerciseWorkout", b =>
                {
                    b.Property<int>("ExercisesExerciseId")
                        .HasColumnType("int");

                    b.Property<Guid>("Workoutsid")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("ExercisesExerciseId", "Workoutsid");

                    b.HasIndex("Workoutsid");

                    b.ToTable("ExerciseWorkout");
                });

            modelBuilder.Entity("workout_planner.Server.Models.Exercise", b =>
                {
                    b.Property<int>("ExerciseId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ExerciseId"));

                    b.Property<string>("ExerciseName")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasColumnName("Exercise");

                    b.Property<string>("musclegrp")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ExerciseId");

                    b.ToTable("Exercise");

                    b.HasData(
                        new
                        {
                            ExerciseId = 1,
                            ExerciseName = "Barbell Curl",
                            musclegrp = "Biceps"
                        },
                        new
                        {
                            ExerciseId = 2,
                            ExerciseName = "Hammer Curl",
                            musclegrp = "Biceps"
                        },
                        new
                        {
                            ExerciseId = 3,
                            ExerciseName = "Skull Crushers",
                            musclegrp = "Triceps"
                        },
                        new
                        {
                            ExerciseId = 4,
                            ExerciseName = "Triceps Pushdown",
                            musclegrp = "Triceps"
                        },
                        new
                        {
                            ExerciseId = 5,
                            ExerciseName = "Plank",
                            musclegrp = "Abs"
                        },
                        new
                        {
                            ExerciseId = 6,
                            ExerciseName = "Hanging Leg Raise",
                            musclegrp = "Abs"
                        },
                        new
                        {
                            ExerciseId = 7,
                            ExerciseName = "Barbell Bench Press",
                            musclegrp = "Chest"
                        },
                        new
                        {
                            ExerciseId = 8,
                            ExerciseName = "Incline Dumbbell Fly",
                            musclegrp = "Chest"
                        },
                        new
                        {
                            ExerciseId = 9,
                            ExerciseName = "Overhead Press",
                            musclegrp = "Shoulders"
                        },
                        new
                        {
                            ExerciseId = 10,
                            ExerciseName = "Lateral Raise",
                            musclegrp = "Shoulders"
                        });
                });

            modelBuilder.Entity("workout_planner.Server.Models.Users", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Roles")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Admin",
                            Password = "admin",
                            Roles = "Admin",
                            Username = "Admin"
                        },
                        new
                        {
                            Id = 2,
                            Name = "User",
                            Password = "user",
                            Roles = "User",
                            Username = "User1"
                        });
                });

            modelBuilder.Entity("workout_planner.Server.Models.Workout", b =>
                {
                    b.Property<Guid>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("WorkoutDescription")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("WorkoutName")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasColumnName("Workout Name");

                    b.HasKey("id");

                    b.ToTable("Workout");
                });

            modelBuilder.Entity("ExerciseWorkout", b =>
                {
                    b.HasOne("workout_planner.Server.Models.Exercise", null)
                        .WithMany()
                        .HasForeignKey("ExercisesExerciseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("workout_planner.Server.Models.Workout", null)
                        .WithMany()
                        .HasForeignKey("Workoutsid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
